### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [michalkow/cssConsole#1]
When browsing demo either in Firefox 16.0.1 (tested in Win/Linux) or 18.0a2 (tested in Linux), and possibly other FF versions/OS's following bugs were encountered:
- No text is displayed in text inputs when typing, though visually cursor position changes
- Bug concerning password input - it doesn't delete asterisks when backspacing
- Can't navigate in input elements using arrow keys - instead it prints one of these (`%&('`) characters

**Comment by michalkow** [comment]
I am sorry, demo on my webpage had a little older version on the plugin, that was using 'keypress' event, it was a little faster, but was not working on Firefox and Opera. 
I updated the demo on my page and now it should work fine.
