### ISSUE TITLE
The caret is not working

### ISSUE THREAD

**Issue by aj07mm** [michalkow/cssConsole#11]
hi,
My caret is not the same as the plugin demo, 
![terminal-fail](https://cloud.githubusercontent.com/assets/3050129/3371524/b5685410-fba1-11e3-9229-1c5d150adc7e.jpg)

i have all the css and js loaded right and i tested in chrome,firefox and ie but they are all the same

**Comment by michalkow** [comment]
Do you have jquery loaded? It is hard for me to help you without seeing your code, can you paste it here or on jsfiddle?

**Comment by aj07mm** [comment]
year i have. I tried with jsfiddle using the minified, the prob continues: http://jsfiddle.net/5YEfJ/

**Comment by michalkow** [comment]
I haven't touch this repo in a while, so I forgot the initialization is a little bit counter intuitive. You don't do that on input element but on empty dom element, and cssConsole creates a hidden input element for you. Here http://jsfiddle.net/5YEfJ/6/

**Comment by aj07mm** [comment]
gotcha! thks!
