### ISSUE TITLE
Can't clear first character in input control with delete key

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [michalkow/cssConsole#2]
There is a minor bug concerning input boxes.
## Steps to reproduce:
1. Type "123" in text or password input control
2. Position cursor at the start of a string, by pressing left arrow on a keyboard three times
3. Press Delete key three times
## Expected result:

All characters are cleared _visually_ (DOM value is indeed correct - "")
## Actual result:

"1" or "*" is left in the input box

_Note: If any other character is typed in this input box correct visual marks are shown_

**Comment by michalkow** [comment]
Fixed.
