### ISSUE TITLE
Home and End keypresses are not respected

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [michalkow/cssConsole#3]
## Steps to reproduce:
1. Type and string into available input controls
2. Position cursor at some non-leftmost or rightmost position
3. Press "Home" or "End" key on a keyboard
## Expected result:

Cursor is moved to the beginning or end of a string
## Actual result:

No action

**Comment by michalkow** [comment]
I added functionality for "home" and "end" keys.
