### ISSUE TITLE
height to high for .cssConsoleCursor

### ISSUE THREAD

**Issue by DanielRuf** [michalkow/cssConsole#7]
it works here with height:14px but a higher value leaves sometimes a fragment of the blinking cursor under the letters

**Comment by michalkow** [comment]
I am not sure what do you mean.
If you change font size you should probably adjust height of cursor and input in css file.
Could you clarify what the problem is?

**Comment by DanielRuf** [comment]
well I see this (using Opera on Windows 7 64bit) sometimes:
![console](http://imageshack.us/a/img853/3636/consolep.jpg)

when I change the css to this:

```
.cssConsoleCursor {
    float: left;
    background: #fefefe;
    width:8px;
    height:14px;
    margin:0;
    padding:0;
    padding-right:1px;
    padding-left:1px;
    visibility: hidden;
}
```

so `height:17px` is too high, it seems to be a problem with the height of the text / line (lineheight?) and then this rendering error happens. changing it to `height:14px` solved it for me

**Comment by michalkow** [comment]
That is interesting. I manged to reproduce this error in Opera. Tried your solution, but then some letters that are "longer" (eg. 'g', 'y', 'j', 'q') are cut on the bottom.

**Comment by DanielRuf** [comment]
I added in the css file for `.cssConsoleDisplay span` the following:

```
height:19px;
line-height:19px;
```

So then it works

the line

```
background: #370f29;
```

can be removed (the whole console has already this background color)
as font color can be also used `transparent` instead of the background color fo the console

also we should definitely set a `font-size` for the console or it falls back to the standard font-size value of the browser on which you can not rely.

**Comment by DanielRuf** [comment]
any news? do you merge these changes?

**Comment by michalkow** [comment]
I did just now, but doesn't seems to fix the problem with the Opera.

**Comment by DanielRuf** [comment]
well the values I used where it worked are

```
height:19px;
line-height:19px;
```

also dont forget the values I changed for `.cssConsoleCursor`
