### ISSUE TITLE
better fonts

### ISSUE THREAD

**Issue by DanielRuf** [michalkow/cssConsole#8]
we could use Source Code Pro and Source Sans Pro from Adobe:

https://github.com/adobe/source-code-pro
https://github.com/adobe/source-sans-pro

We can use then the fontface generator from fontsquirrel.com

**Comment by michalkow** [comment]
Courier is a standard font and fits demonstration/example purposes.
You are free to use any fonts you want for your project with cssConsole.

**Comment by DanielRuf** [comment]
sure, was just a suggestion =) find them much better than the plain courier font
