### ISSUE TITLE
periodic focus prevents browsing

### ISSUE THREAD

**Issue by DanielRuf** [michalkow/cssConsole#9]
this code should be deleted from the console example or we cant browse on the page because of the autofocus every 100ms

```
focus = window.setInterval(function() {
if(!$('#input').find('input').is(":focus")){
    $('#input').find('input').focus();
}
}, 100);
```

**Comment by michalkow** [comment]
Updated the example with better focus settings.

**Comment by DanielRuf** [comment]
much better =)
